spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    redis:
      host: thingdong.com
      port: 1234
      repositories:
        enabled: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://thingdong.com:5555/ssafy_b304?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssafy_b304
    password: ssafy_b304_1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 10
        format_sql: true
    show-sql: true
    open-in-view: false

logging:
  level:
    com.bell.thingdong: debug
    org:
      hibernate: info

jwt:
  key: fsdnvnskvnnfnvfksdvfgvkbnsdjflbajkdvsdnfklsndvklnfsdvkkdlsfnklsfdvnkl

server:
  ec2-url: https://thingdong.com
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ssafy
    key-store-type: PKCS12

translator:
  papago:
    url: https://openapi.naver.com/v1/papago/n2mt
    client-id: Q4sb0BCOsE0xX3M19V8J
    client-secret: a5h1RIcsLF
generator:
  stable-diffusion:
    url: http://k9b304.p.ssafy.io
    port : 8888
