spring:
  data:
    redis:
      host: thingdong.com
      port: 1234

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://thingdong.com:5555/ssafy_b304?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssafy_b304
    password: ssafy_b304_1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 10
        format_sql: true
    show-sql: true
    open-in-view: false

logging:
  level:
    com.bell.thingdong: DEBUG
    org:
      hibernate: debug

jwt:
  key: fsdnvnskvnnfnvfksdvfgvkbnsdjflbajkdvsdnfklsndvklnfsdvkkdlsfnklsfdvnkl
