version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      args:
        SERVER_MODE: prod
    networks:
      - deploy

networks:
  deploy:
    external: true
