version: "3.8"

services:
  backend:
    container_name: smartthings
    build:
      context: ./smartthings
    networks:
      - deploy
    ports:
      - "9000:9000"

networks:
  deploy:
    external: true

